networks:
  frontend:
    name: frontend-network
  backend:
    name: backend-network
    external: false

volumes:
  mysql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: D:\docker\data\mysql_data_volume

services:
  # docker run --name:db -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=bob -e MYSQL_DATABASE=wordpress 
  # -e MYSQL_USER=toto -e MYSQL_PASSWORD=toto mysql:latest
  database:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=bob
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=toto
      - MYSQL_PASSWORD=bob
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
      #- D:\docker\data\mysql_data_volume:/var/lib/mysql
  myadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.3-apache
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=bob
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
    networks:
      - frontend
      - backend
